### ISSUE TITLE
SDK not support PandarXT-32???

### ISSUE THREAD

**Issue by dungcules** [HesaiTechnology/HesaiLidar_General_SDK#10]
I am having a PandarXT-32 and I am working on reading udp package from this Lidar and writing to file. I changed the UDP address to cast into 1 station which is my computer only. I am able to connect to the lidar but when I try to read from this lidar, most of polling value return 0 which mean there is not data to read. The port that I used is 2368 which is the same as setting on web interface. Do I miss anything to receive the data from this Lidar??

**Comment by zyxcambridge** [comment]
YES，
