### ISSUE TITLE
Standby Mode

### ISSUE THREAD

**Issue by dagata-mining** [HesaiTechnology/HesaiLidar_General_SDK#25]
Hi,

I'm trying to put my PANDARXT in standby mode via the API but does not seem to have any command. Any idea on how to do it?

**Comment by yangfanFred** [comment]
> Hi,
> 
> I'm trying to put my PANDARXT in standby mode via the API but does not seem to have any command. Any idea on how to do it?

Hi @dagata-mining , does it mean you don't have the HTTP and TCP API manual? Please contact your sales man to get those manuals.

**Comment by dagata-mining** [comment]
Hi,
Yes it's exactly what it means, I'm trying to get it but no answers from
frank.bertini@hesaitech.com any other way I could get it?

**Comment by dagata-mining** [comment]
Finally, the TCP protocol was not the right version. Got the right one and now is working. So any one struggling with this problem  you need to implement a new tcp call in tcp_command_client.c Here's my snipped of code (you'll also need to update the header and implement the)

```cpp
PTC_ErrCode TcpCommandSetStandby(const void* handle, int on)
{
    if (!handle)
    {
        printf("Bad Parameter!!!\n");
        return PTC_ERROR_BAD_PARAMETER;
    }
    TcpCommandClient *client = (TcpCommandClient *) handle;

    char *buffer;
    if (on == 1)
    {
        buffer[0] = 0;
    }
    else
    {
        buffer[0] = 1;
    }

    TC_Command cmd;
    memset(&cmd, 0, sizeof(TC_Command));
    cmd.header.cmd = 0x1c;
    cmd.header.len = 1;
    cmd.data = strdup(buffer);

    PTC_ErrCode errorCode = tcpCommandClient_SendCmd(client, &cmd);
    if (errorCode != PTC_ERROR_NO_ERROR) {
        free(cmd.data);
        return errorCode;
    }
    free(cmd.data);

    if (cmd.ret_data) {
        // useless data;
        free(cmd.ret_data);
    }

    return cmd.header.ret_code;
}


```

and also create a new function in the sdk pandarGeneral_sdk.cc

```cpp
void PandarGeneralSDK::StandBy(bool standBy)
{
    if (!tcp_command_client_)
    {
        return;
    }
    std::cout << "StandBy Mode Called" << std::endl;
    int32_t ret = 0;
    if (standBy)
    {
        ret = TcpCommandSetStandby(tcp_command_client_,0 );
    }
    else
    {
        ret = TcpCommandSetStandby(tcp_command_client_, 1);
    }
    if (ret == 0)
    {
        std::cout << "StandBy Mode Activated" << std::endl;
    }

}
```

**Comment by yangfanFred** [comment]
@dagata-mining Great job, thanks for sharing
